# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sand < Formula
  desc "Headless + TUI manager for Claude Code development VMs (Lima)"
  homepage "https://github.com/lullabot/sandbar"
  version "0.6.0"

  depends_on "lima"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Lullabot/sandbar/releases/download/v0.6.0/sandbar_0.6.0_darwin_amd64.tar.gz"
      sha256 "18e1f32b668f05272c96cb1f50d51451e206944a8852db02a7e36653d4ceda20"

      define_method(:install) do
        bin.install "sand"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Lullabot/sandbar/releases/download/v0.6.0/sandbar_0.6.0_darwin_arm64.tar.gz"
      sha256 "ca65e2c81a948f1501aeac7e45f519c3c2135cbec5f9b53e21c328300ec71ac7"

      define_method(:install) do
        bin.install "sand"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lullabot/sandbar/releases/download/v0.6.0/sandbar_0.6.0_linux_amd64.tar.gz"
      sha256 "a5319db2c869061360c33a65e81f15b18a76c878005507bf4436e92a2c028284"
      define_method(:install) do
        bin.install "sand"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lullabot/sandbar/releases/download/v0.6.0/sandbar_0.6.0_linux_arm64.tar.gz"
      sha256 "c63be1d459c6b7d0386e0f245f2fd3ea30f8236f55e500d069d7839a40de05fc"
      define_method(:install) do
        bin.install "sand"
      end
    end
  end
end
